name: hello world idev

on:
  push:
    branches:
      - '**'

jobs:
  hello-world-idev:
    runs-on: self-hosted
    steps:
      - run: |
          idev idev -N 2 --ntasks-per-node=1
          echo "hello world from $(hostname)"
          exit