name: hello world sbatch

on:
  push:
    branches:
      - '**'

jobs:
  hello-world-sbatch:
    runs-on: self-hosted
    steps:
      - run: |
          sbatch <<'EOF'
          #!/bin/bash

          #SBATCH --partition=kamiak
          #SBATCH --job-name=hello-world-batch
          #SBATCH --output=~/myJob_%j.out
          #SBATCH --error=~/myJob_%j.err
          #SBATCH --nodes=1
          #SBATCH --ntasks-per-node=1
          #SBATCH --ntasks=1
          #SBATCH --cpus-per-task=1

          echo "hello world from $(hostname)"
          EOF