name: hello world sbatch

on:
  push:
    branches:
      - '**'

jobs:
  hello-world-sbatch:
    runs-on: self-hosted
    steps:
      - run: |
          sbatch \
            #!/bin/bash \
            --job-name=github-actions \
            --ntasks=1 \
            --cpus-per-task=1 \
            srun echo "hello world from $(hostname)"